#!/usr/bin/env node
/**
 * Generate THIRD-PARTY-NOTICES.md from what is actually installed.
 *
 * Distributing a binary means distributing these dependencies, and most of their
 * licences (MIT, BSD, ISC, Apache-2.0) require the copyright notice and licence
 * text to travel with the software. electron-builder does not do this, so
 * without a generated notices file the AppImage and the installer ship in breach
 * of licences that are otherwise trivial to comply with.
 *
 * Run after changing dependencies:
 *   node tools/generate-notices.mjs
 *
 * Walks the runtime dependency tree from package.json `dependencies`, plus the
 * platform-specific optional packages that are present (sharp's libvips
 * binaries, which are the only copyleft component bundled).
 */
import { readFileSync, existsSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()
const NM = join(ROOT, 'node_modules')

const LICENSE_FILES = [
  'LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENCE', 'LICENCE.md',
  'LICENSE-MIT', 'LICENSE-APACHE', 'COPYING', 'COPYING.md'
]

function readPkg(name) {
  const p = join(NM, name, 'package.json')
  if (!existsSync(p)) return null
  try {
    return JSON.parse(readFileSync(p, 'utf8'))
  } catch {
    return null
  }
}

function licenseText(name) {
  const dir = join(NM, name)
  for (const f of LICENSE_FILES) {
    const p = join(dir, f)
    if (existsSync(p)) {
      try {
        return readFileSync(p, 'utf8').trim()
      } catch {
        /* unreadable, fall through */
      }
    }
  }
  return null
}

function spdx(pkg) {
  if (typeof pkg.license === 'string') return pkg.license
  if (pkg.license?.type) return pkg.license.type
  if (Array.isArray(pkg.licenses)) return pkg.licenses.map((l) => l.type).join(' OR ')
  return 'UNKNOWN'
}

/** First plausible copyright line, so the attribution survives even when we summarise. */
function copyrightLine(text) {
  if (!text) return null
  const line = text
    .split('\n')
    .map((l) => l.trim())
    .find((l) => /^(copyright|\(c\)|©)/i.test(l) && l.length < 200)
  return line || null
}

const collected = new Map()

function walk(name) {
  if (collected.has(name)) return
  const pkg = readPkg(name)
  if (!pkg) return
  const text = licenseText(name)
  collected.set(name, {
    version: pkg.version ?? '?',
    license: spdx(pkg),
    homepage: pkg.homepage || (typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url) || null,
    text,
    copyright: copyrightLine(text)
  })
  // optionalDependencies must be followed, not just dependencies. Native
  // binaries are shipped that way: inspecting a packaged build turned up
  // @napi-rs/canvas (Skia), pulled in optionally by pdfjs-dist, which a
  // dependencies-only walk missed entirely even though it lands in the asar.
  for (const dep of Object.keys(pkg.dependencies ?? {})) walk(dep)
  for (const dep of Object.keys(pkg.optionalDependencies ?? {})) walk(dep)
}

const rootPkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
for (const dep of Object.keys(rootPkg.dependencies ?? {})) walk(dep)
for (const dep of Object.keys(rootPkg.optionalDependencies ?? {})) walk(dep)

// Scoped platform packages are installed as siblings rather than being reachable
// from the tree at all on some npm versions, so sweep the scopes that hold
// native binaries directly.
for (const scope of ['@img', '@napi-rs']) {
  const dir = join(NM, scope)
  if (existsSync(dir)) {
    for (const entry of readdirSync(dir)) walk(`${scope}/${entry}`)
  }
}

// Electron itself is a devDependency but its runtime ships in every artifact.
walk('electron')

const names = [...collected.keys()].sort()
const byLicense = new Map()
for (const n of names) {
  const l = collected.get(n).license
  if (!byLicense.has(l)) byLicense.set(l, [])
  byLicense.get(l).push(n)
}

const out = []
out.push('# Third-party notices')
out.push('')
out.push('Kopibon is licensed under GPL-3.0-or-later (see `LICENSE`). It')
out.push('bundles the third-party packages listed here, each under its own licence.')
out.push('')
out.push('Generated by `node tools/generate-notices.mjs`. Do not edit by hand.')
out.push('')
out.push(`Packages: ${names.length}`)
out.push('')

out.push('## Licences in use')
out.push('')
out.push('| Licence | Packages |')
out.push('| --- | --- |')
for (const [lic, pkgs] of [...byLicense.entries()].sort((a, b) => b[1].length - a[1].length)) {
  out.push(`| ${lic} | ${pkgs.length} |`)
}
out.push('')

out.push('## Copyleft components')
out.push('')
const copyleft = names.filter((n) => /GPL|MPL|EPL|CDDL/i.test(collected.get(n).license))
if (copyleft.length === 0) {
  out.push('None bundled.')
} else {
  for (const n of copyleft) {
    const info = collected.get(n)
    out.push(`- **${n}** ${info.version} - ${info.license}`)
  }
  out.push('')
  out.push('These are compatible with GPL-3.0: LGPL-3.0 is GPL-3.0 plus additional')
  out.push('permissions, so combining it with a GPL-3.0 application is expressly allowed.')
  out.push('Their full licence text is reproduced in the per-package section below, and')
  out.push('the corresponding source is available from each project.')
}
out.push('')

out.push('## Tools invoked but not bundled')
out.push('')
out.push('The app shells out to these. They are installed by the user (or by dnf for the')
out.push('RPM build) and are **not** redistributed with it, so no notice obligation')
out.push('attaches to them. Listed for completeness:')
out.push('')
out.push('| Tool | Licence | Used for |')
out.push('| --- | --- | --- |')
out.push('| poppler (`pdfinfo`, `pdfimages`, `pdftoppm`) | GPL-2.0/GPL-3.0, LGPL-2.x, MIT | PDF thumbnails and PDF to CBZ conversion |')
out.push('| pikepdf | MPL-2.0 | Writing PDF XMP metadata |')
out.push('| Python 3 | PSF (Python-2.0) | Runs pikepdf |')
out.push('')
out.push('Bundling poppler binaries in future would mean distributing GPL code. That is')
out.push('permitted because this app is GPL-3.0, but it would add a source-offer')
out.push('obligation for poppler as well.')
out.push('')

out.push('## Packages')
out.push('')
for (const n of names) {
  const info = collected.get(n)
  out.push(`### ${n} ${info.version}`)
  out.push('')
  out.push(`Licence: ${info.license}`)
  if (info.homepage) out.push(`Homepage: ${info.homepage.replace(/^git\+/, '').replace(/\.git$/, '')}`)
  out.push('')
  if (info.text) {
    out.push('```')
    out.push(info.text)
    out.push('```')
  } else if (info.copyright) {
    out.push(info.copyright)
  } else {
    out.push(`No licence file shipped in the package; see the ${info.license} licence and the project homepage.`)
  }
  out.push('')
}

writeFileSync(join(ROOT, 'THIRD-PARTY-NOTICES.md'), out.join('\n'))
console.log(`THIRD-PARTY-NOTICES.md written: ${names.length} packages, ${byLicense.size} distinct licences`)
if (copyleft.length > 0) {
  console.log(`copyleft components: ${copyleft.join(', ')}`)
}
